lowercasename/gathio

- app.js
- config/domain-example.js
- routes.js
- views/emails/addeventattendee.handlebars
- views/emails/addeventcomment.handlebars
- views/emails/createevent.handlebars
- views/emails/createeventgroup.handlebars
- views/emails/deleteevent.handlebars
- views/emails/editevent.handlebars
- views/emails/removeeventattendee.handlebars
- views/emails/unattendevent.handlebars
- views/layouts/email.handlebars
Tons of refactoring of email. This no longer uses Sendgrid templates and now uses source-controlled handlebars files in the `views/emails/` directory. This means that email messages are now source-controlled and vastly reduces the sendgrid setup process.
I based the email text (mostly) on what https://gath.io currently sends out to attendees/organizers.
This also adds a new file, `domain-example.js`, in the config directory, which stores things like the site name, base URL, port, etc. This should be renamed to `domain.js`, in keeping with the other configuration files.
Email template is a modified version of this [Responsive HTML Email Template](https://github.com/leemunroe/responsive-html-email-template).
> Refactor email to use source-controlled templates

- routes.js
In the case where a Gathio server upgrades to the version supporting ActivityPub, there can be errors related to missing ActivityPub actors for old events. This fixes that bug. I *believe* this will fix the issues I'm having federating with https://gath.io right now.
> Adding failsafe for misssing AP data

- views/eventgroup.handlebars
> If you'll add #groupEvents to a div showing upcoming events you'll be able to share links scrolled straight to event list of your event group. It might come very handy for example when you embed it in <iframe> tag.
> Example url that scrolls automatically to an event list: https://gath.io/group/0HSOEdrcw#groupEvents
I personally think this can come really handy when you want to embed your events group on a website or share a straight link to upcoming events. And it's just a matter of adding a simple id selector in HTML file.
> Anchor upcoming events

- views/event.handlebars
There are names shorter than 3 characters such as "Jo", I don't see any reason for the minimum to be 3.
> Allow names to be less than 3 characters

- activitypub.js
- routes.js
- views/event.handlebars
Append editToken to the deleteEvent form action to fix 404 error on event deletion.
Refactor broadcastDeleteMessage so that eventDeletion works when federation is disabled. There's probably a less hacky way to do this.
Send deletion emails within the callback, otherwise DB lookup fails on deleted event id.
Fixes #84
> Fix event deletion

- views/event.handlebars
As referenced in https://github.com/lowercasename/gathio/issues/90
Added the invisible class names that make up the microformat requirements for an "h-event"
http://microformats.org/wiki/h-event
Including:
- p-name
- p-summary
- dt-duration
- p-location
- u-url
I tested it using the Go Microformats Parser: https://go.microformats.io
And it parses and renders correctly!
> ✨ add h-event microformat markup

- package.json
- pnpm-lock.yaml
The previous ^-based `typescript` version string in `package.json` installed 5.2.x automatically, but some changes in 5.2 break the build. I have updated this to explicitly install the latest 5.1 version, one that I have confirmed to work
I believe this fixes #107
> Update typescript version

- src/activitypub.js
Applying the new `indexable` attribute (and the old `discoverable` attribute) to the main ActivityPub actor for a Gathio page as described here: https://github.com/mastodon/mastodon/pull/26485
Setting everything to false since Gathio is private-by-default.
Using the `toot` namespace since that seems safe enough. This commit from the Pixelfed repo making their service compatible with `indexable` is a good reference, but also we don't need to create our own namespace like they did. https://github.com/pixelfed/pixelfed/pull/4612
Fixes #116
> Disable discoverability/indexablity for ActivityPub actors

- views/emails/createEventGroup/createEventGroupHtml.handlebars
- views/emails/createEventGroup/createEventGroupText.handlebars
The links in the HTML emails worked fine, but the displayed URLs were missing the “group” part.
And in text version of the emails the links won't work (eg. if you copy/paste them).
> Fixed URLs in createEventGroup emails

- cypress/e2e/event.cy.ts
- src/activitypub.js
- src/app.ts
- src/lib/activitypub.ts
- src/routes.js
- src/routes/frontend.ts
According to the ActivityPub spec:
> The HTTP GET method may be dereferenced against an object's id property to retrieve the activity. Servers MAY use HTTP content negotiation as defined in [[RFC7231](https://www.w3.org/TR/activitypub/#bib-RFC7231)] to select the type of data to return in response to a request, but MUST present the ActivityStreams object representation in response to `application/ld+json; profile="https://www.w3.org/ns/activitystreams"`, and SHOULD also present the ActivityStreams representation in response to `application/activity+json` as well. The client MUST specify an Accept header with the `application/ld+json; profile="https://www.w3.org/ns/activitystreams"` media type in order to retrieve the activity.
This PR standardizes the use of `Accept` and `Content-Type` …
> Send and accept only spec-compliant ActivityPub headers

- package.json
- src/routes/activitypub.ts
This adds a `/.well-known/nodeinfo` endpoint to support the [NodeInfo standard](https://github.com/jhass/nodeinfo).
> Add NodeInfo

- config/config.example.toml
- public/js/modules/new.js
- src/app.ts
- src/lib/config.ts
- src/lib/email.ts
- src/lib/middleware.ts
- src/models/MagicLink.ts
- src/routes/event.ts
- src/routes/frontend.ts
- src/routes/group.ts
- src/routes/magicLink.ts
- src/util/generator.ts
- views/createEventMagicLink.handlebars
- views/emails/createEventMagicLink/createEventMagicLinkHtml.handlebars
- views/emails/createEventMagicLink/createEventMagicLinkText.handlebars
- views/partials/eventForm.handlebars
- views/partials/eventGroupForm.handlebars
- views/partials/importeventform.handlebars
This fulfills the feature request in https://github.com/lowercasename/gathio/issues/1 (our first ever issue! Better late than never!) to optionally restrict event creation to a set of whitelisted email addresses.
In the config file you can now specify an array:
```
creator_email_addresses = ["test@test.com", "admin@test.com"]
```
If this array is not blank, navigating to `/new` will instead navigate to a form where the user can enter their email address. If that email address is in the whitelist, they get an email with a magic link (saved in a new `magiclinks` collection in the database), which will allow them to go to the actual event/group creation forms. Whether the email exists or not, the user gets the same success message back, to prevent enumeration attacks.
Magic links are only …
> Optionally restrict event creation to specific email addresses

- config/config.example.toml
- src/lib/config.ts
- src/routes.js
Using the config file option `delete_after_days`, users can now specify how many days to wait before concluded events are deleted. The default is 7, and if the option is set to 0, events will be stored permanently and never auto-deleted.
> Set number of days to store concluded events (including permanently!)

- README.md
- deploy.sh
- docs/index.md
- docs/running-gathio/configuration.md
- docs/running-gathio/customization.md
- docs/running-gathio/installation.md
- docs/using-gathio/fediverse.md
- mkdocs.yml
Moving the docs from the GitHub wiki to a `docs/` folder, which can be source-controlled. They'll be hosted using MkDocs on https://docs.gath.io.
> Add docs using MkDocs

- cypress/e2e/event.cy.ts
- pnpm-lock.yaml
- src/routes.js
- src/routes/event.ts
- src/routes/frontend.ts
- src/util/generator.ts
- src/util/messages.ts
- views/emails/addEventAttendee/addEventAttendeeHtml.handlebars
- views/emails/addEventAttendee/addEventAttendeeText.handlebars
- views/emails/unattendEvent/unattendEventHtml.handlebars
- views/emails/unattendEvent/unattendEventText.handlebars
- views/event.handlebars
Adds a new feature as suggested in https://github.com/lowercasename/gathio/issues/145: when the RSVP email is sent to an attendee, it contains a link to quickly un-RSVP from the event. The link leads to a new endpoint which takes the event ID and the hash of the RSVP password.
I also added the beginnings of a library to show error/success messages on pages.
> Unattend events from RSVP email

- config/config.example.toml
- package.json
- public/css/style.css
- public/js/modules/event-edit.js
- public/js/modules/group-edit.js
- public/js/modules/new.js
- src/lib/config.ts
- src/routes/frontend.ts
- src/routes/static.ts
- static/instance-description.md
- views/createEventMagicLink.handlebars
- views/event.handlebars
- views/eventgroup.handlebars
- views/home.handlebars
- views/newevent.handlebars
- views/partials/editeventgroupmodal.handlebars
- views/partials/editeventmodal.handlebars
- views/partials/eventForm.handlebars
- views/partials/importeventform.handlebars
- views/partials/instanceRules.handlebars
- views/partials/sidebar.handlebars
- views/publicEventList.handlebars
This switches out the base Bootstrap styling for some more unique styles to give Gathio a more standalone identity. It also adds Alpine.js in a bid to slowly replace all the jQuery code with Alpine.js code, which I greatly prefer, de-emphasises the editing buttons on public event pages for clarity, per the suggestion in https://github.com/lowercasename/gathio/issues/140, and fixes textareas in editing modals as per https://github.com/lowercasename/gathio/issues/152.
> Style overhaul

- .github/workflows/ci.yaml
- .github/workflows/deploy.yaml
- src/lib/event.ts
- src/routes/frontend.ts
- views/eventgroup.handlebars
- views/partials/eventList.handlebars
- views/publicEventList.handlebars
Creates a Handlebars partial to improve reproducibility and buckets events by months.
> Improve event lists

- src/lib/email.ts
Added "tls:" property of  'rejectUnauthorized: false' to allow program to continue startup when SMTP certificates are not able to be validated against known trusted roots.
> Allow self-signed certs for SMTP server

- docker-compose.yml
Added docker-compose example for mounting a volume for the /app/public/events directory. This can be helpful because rebuilding the docker image per instructions causes user-uploaded images to be lost. Using a persistent volume prevents this data loss when rebuilding.
> Docker volume for 'events' folder

- src/activitypub.js
- views/home.handlebars
This updates the landing page, and also ActivityPub responses containing links to the Fediverse instructions, to point to the new docs site instead of to the wiki.
> Change wiki links to new docs site.

- views/event.handlebars
The replyAuthor placeholder template has an extra Y in it so it renders as (eg in english) "YYour Name". This commit deletes the extra Y.
> Fix typo in comment placeholder text

- views/event.handlebars
- views/eventgroup.handlebars
use mimetype `txt/calendar` when downloading the .ics file.
Resolves lowercasename#190
> Fix download of ICS file
